### ISSUE TITLE
Set width and height for takePhoto

### ISSUE THREAD

**Issue by Importeer** [tony-xlh/capacitor-plugin-camera-preview#1] opened 2022-11-30 16:47 UTC
Hi guys,

I'm using your fork because of the better setFocus function. I'm heaving two problems with the code.

1. Is it possible to set a Width / Height (and maybe for some; Quality) for the takePhoto function? Right now my picture is 3264x2448 and 1.7MB. 

2. If i use the takePhoto function, everything is good. When i want to take another picture (without leaving the Camera Preview) the code will not produce a base64 string and becomes silent. Can you reproduce this?

Thanks in advance!

Alex

**Comment by xulihang** [comment] 2022-12-01 01:55
The plugin is based on [Dynamsoft Camera Enhancer](https://www.dynamsoft.com/camera-enhancer/docs/introduction/). We have to wait for them to add the width and height settings.

About the second issue, I will try to reproduce this.

**Comment by xulihang** [comment] 2024-09-05 02:54
I am closing this since I've been working on a new package using native APIs directly: https://www.npmjs.com/package/capacitor-plugin-camera

**Closed as completed by xulihang** 2024-09-05 02:54 UTC
